### ISSUE TITLE
Add support for Logic App template

### ISSUE THREAD

**Issue by johnnliu** [BrianFarnhill/generator-arm-template#1]
MS Flow can export to logic app json as well.  I think that's just a ARM template we can embed with this.  Need to deploy with different connections.

**Comment by BrianFarnhill** [comment]
@johnnliu I think it is a good idea to add logic apps in here as a basic starter that you could then paste the export of MS flow in to. Lets add logic app templates to the backlog and see what we can do from there. Thanks mate

**Comment by BrianFarnhill** [comment]
@johnnliu Have a look at #4 to see if the template that comes out of the code there cuts it for you. Specifically, check the [_addResource() function](https://github.com/BrianFarnhill/generator-arm-template/pull/4/files#diff-89cb4f899c67bce6d17f51375d6f5f9dR64).
